#!/bin/bash
# Start INT and/or EXT on AWS using AWS CLI
# uses credentials and config files in /home/eace/.aws/

if [[ "$#" == 0 ]]
then
	echo "Specify the instance(s) to start in arg(s) 1 - n from the following list of known instances: INT, EXT"
	echo "E.g. start-instance EXT INT"
	exit 1
fi

for instance in "$@"
do
    if [[ $instance == "INT" ]]
    then
        echo "echo Starting $instance..."
        aws ec2 start-instances --instance-ids i-0c86feebb43bbd9e2
    elif [[ $instance == "EXT" ]]
    then
        echo "echo Starting $instance..."
        aws ec2 start-instances --instance-ids i-0975ee90a4919349e
    else
        echo "Unknown instance name: $instance -- ignoring..."
    fi
done
