#!/bin/bash
#
# Prints system info by invoking shell commands. Tested on
# Ubuntu 18.04.3 LTS, GNU bash, version 4.4.20(1)-release
# (x86_64-pc-linux-gnu)
#
# Note:
#
# This script uses pass-by-reference functionality in some functions
# by virtue of local function variable decls using the '-n' flag.
# See: 'https://www.gnu.org/software/bash/manual/html_node/Shell-Parameters.html'
# for info.
#
# TODO:
#  - lspci
#  - findmnt
#  - df
#  - du
#  - free
#  - lscpu
#  - lshw
#  - fdisk
#  - hwinfo
#  - dmidecode? (docs say info is often inaccurate)

#
# Supported cmd-line options
#
short_opts=hmbpa
long_opts=help,mounts,blockdevs,partitions,all
script_name=$(basename "$0")

#
# A list of the functions to call, based on the passed params. Populated
# by the 'parse_args' function
#
infos=()

#
# Prints usage instructions
#
# Params:
#
#   None
#
# Returns:
#
#   Nothing
#
function usage() {
  while IFS= read -r line; do
    echo "${line:4}"
  done <<< '
    Prints system information, as determined by the passed args. Sudo
    should be used to get all available info. (Some commands invoked
    by the script require sudo.)
    
    Usage: sysinfos [-h,--help] [-m,--mounts] [-p,--partitions]
           [-b,--blockdevs] [-a,--all]
    
    Options:
    
      -m,--mounts      Prints mounts via the '"'mount'"' command
      -p,--partitions  Prints the partition table for each disk
                       via the '"'parted'"' command
      -b,--blockdevs   Prints block devices via the '"'lsblk'"' command
      -a,--all         Prints all system infos listed above
      -h,--help        Prints this help and exits

    Examples:
    
      suso sysinfos -a
      
      Prints all system information
    '
}

#
# Parses the command line and sets script variables
#
# Params:
#
#   $@ - The entire command line
#
# Returns:
#
#   Nothing
#
# Exits:
#
#   With an error message to the console if there is a parse error
#
# Sets script variables:
#
#   infos -- Based on the command-line options, this will contain a list
#            of functions to call matching the defined arg. E.g. if "-b"
#            is specified, then this variable will contain "blkdevs" - which
#            is the function that prints info about block devices.
#

function parse_args() {
  local parsed=$(getopt --options $short_opts --longoptions $long_opts -n $script_name -- "$@")

  if [[ "$?" -ne 0 ]]; then
    exit 1
  fi

  eval set -- "$parsed"

  local supported_infos=(blkdevs mounts partitions)
  
  while true; do
    case "$1" in
      -h|--help)
        usage
        exit 1
        ;;
      -a|--all)
        infos=("${supported_infos[@]}")
        shift "$#"  # empty the command line
        break
        ;;
      -b|--blkdevs)
        infos=($infos ${supported_infos[0]})
        shift 1
        ;;
      -m|--mounts)
        infos=($infos ${supported_infos[1]})
        shift 1
        ;;
      -p|--partitions)
        infos=($infos ${supported_infos[2]})
        shift 1
        ;;
      --)
        shift
        break
        ;;
    esac
  done

  if [[ $# -ne 0 ]]; then
    echo "$script_name: No positional params are supported"
    exit 1
  fi
  if [[ ${#infos[@]} -eq 0 ]]; then
    echo "$script_name: No infos were specified - nothing to do"
    exit 1
  fi
}

#
# utility functions
#

#
# Prints a header from the passed args. The args are expected in
# pairs, in which the first pair value is a header, and the second
# pair value is the length to pad the header to. The headers are
# printed with an underline, and are aligned to the passed lengths,
# plus one for a spacer.
#
# Params:
#
#   A variable length list of header/length pairs
#
# Returns:
#
#   Nothing
#
# Example:
#
#   print_hdr THIS 10 IS 5 A 4 "HEADER LINE" 15
#
#   Would print this to the console:
#
#   THIS       IS    A    HEADER LINE
#   ---------- ----- ---- ---------------
#
function print_hdr() {
  local args=("$@")
  local uline=$(printf "%0.s-" {1..500})
  local hdr_line=""
  local under_line=""
  for ((i = 0; i < ${#args[@]}; i+=2)); do
    hdr="${args[$i]}"
    len=${args[(($i+1))]}
    hdr=$(printf "%-${len}s" "$hdr")
    hdr_line="$hdr_line$(printf "%-${len}s" "$hdr")"
    under_line="$under_line$(echo ${uline::$((len-1))}) "
  done
  echo -e "$hdr_line\n$under_line"
}

#
# Calculates the length of each element in the passed col array. If
# the length exceeds the length at the same position in the passed
# lengths array, then updates the length in the length array from the
# length of the column element. Thus, calling this function in a loop
# with column arrays containing various length elements will result
# in the calculation of the max length of each position. This can
# then be used to format a columnar output.
#
# Params:
#
#   $1 - an array of column lengths. E.g. (14 2 11 5)
#   $2 - an arry of column values. E.g. (this is some data)
#
# Returns:
#
#   The potentially updated array in $1
#
# Example:
#
# lens=(5 2 8)
# cols=(AA BBBBB CCC)
# lens=($(calc_lens lens cols))
# echo "${lens[@]}"
#
# The result would print: '5 5 8' because only the second column
# had a greater length then the passed lengths.
#
function calc_lens() {
  local -n len_array=$1
  local -n col_array=$2
  for ((i = 0; i < ${#col_array[@]}; i++)); do
    [[ ${#col_array[$i]} -gt ${len_array[$i]} ]] && len_array[$i]=${#col_array[$i]}
  done
  echo ${len_array[@]}
}

#
# Prints the passed value array to the console, formatting each
# element to the width specified in the same lengths array at the
# same array offset. The passed widths are increased by two to add
# some spacing.
#
# Params:
#
#   $1 - A value array. E.g. (foo bar baz)
#   $2 - A length array matching the passed value array. E.g.:
#        (10, 5 8)
#   $3 - If 'true', then print an underline under the passed line. If
#        'false' or not provided, then don't print an underline.
#
# Returns:
#
#   Nothing
#
# Example:
#
#   values=(foo bar baz)
#   lengths=(10 5 8)
#   print_line values length "true"
#
#   Would produce the following console output:
#
#   foo         bar    baz
#   ----------  -----  --------
#
function print_line() {
  local -n _values=$1
  local -n _lens=$2
  local underline="${3:false}"
  local fmt=""
  for len in "${_lens[@]}"; do
    ((len+=2))
    fmt="$fmt%-${len}s"
  done
  printf "$fmt\n" "${_values[@]}"
  if [[ "$underline" == "true" ]]; then
    local uline=$(printf "%0.s-" {1..500})
    local under_line=""
    for len in "${_lens[@]}"; do
      under_line="$under_line$(echo ${uline::$len})  "
    done
    echo "$under_line"
  fi
}

#
# Extracts values from the passed line of name/value pairs, and
# stores them in the passed array which the caller passes by ref.
#
# Params:
#
#   $1 - a value array to populate. The function populate this array
#        by reference,
#   $2 - an array of names, to enable the function to get the values.
#        E.g.: (NAME KNAME TYPE FSTYPE MOUNTPOINT UUID SIZE LABEL)
#   $3 - a line of name value pairs, e.g.: NAME="sda" KNAME="sda"
#        TYPE="disk" FSTYPE="" MOUNTPOINT="" UUID="" SIZE="465.8G" LABEL=""
#
# Returns:
#
#   Nothing
#
# Changes:
#
#   Populates the array refernced by $1 (which the caller should pass
#   as an empty array - the function does not initialize it). Using the
#   param examples above, the array would look like: ("sda" "sda" "disk"
#   "" "" "" "465.8G" "")
#
function extract_values() {
  local -n vals=$1
  local -n nms=$2
  local line="$3"
  for nvp in "$line"; do
    for nm in ${nms[@]}; do
      regex=".*$nm=\"([^\"]*)\""
      [[ $line =~ $regex ]]
      vals=("${vals[@]}" "${BASH_REMATCH[1]}")
    done
  done
}

#
# info printing functions - one per supported cmd-line arg
#

#
# Prints block devices, via the 'lsblk' command
#
# Params:
#
#   None
#
# Returns:
#
#   Nothing
#
function blkdevs() {
  local names=(NAME KNAME TYPE FSTYPE MOUNTPOINT UUID SIZE LABEL)
  local lengths=(0 0 0 0 0 0 0 0)
  lengths=($(calc_lens lengths names))
  # TODO store in a simulated 2D array so we don't have to invoke lsblk twice?
  while IFS= read -r line; do
    output=()
    extract_values output names "$line"
    lengths=($(calc_lens lengths output))
  done < <(lsblk -o NAME,KNAME,TYPE,FSTYPE,MOUNTPOINT,UUID,SIZE,LABEL -P | grep -v loop)
  echo -e "BLOCK DEVICES (lsblk)\n"
  print_line names lengths true
  while IFS= read -r line; do
    output=()
    extract_values output names "$line"
    print_line output lengths
  done < <(lsblk -o NAME,KNAME,TYPE,FSTYPE,MOUNTPOINT,UUID,SIZE,LABEL -P | grep -v loop)
}

#
# Prints partition tables, via the 'parted' command
#
# Params:
#
#   None
#
# Returns:
#
#   Nothing
#
function partitions() {
  local lines=()
  local is_dev=false
  local dev_line=
  while IFS= read -r line; do
    if [[ -z "$line" ]]; then
      :
    elif [[ "$line" == "BYT;" ]]; then
      is_dev=true
    elif [[ $is_dev == true ]]; then
      dev_line="${line:0:-1}"
      is_dev=false
    else
      lines=("${lines[@]}" "$dev_line${line:0:-1}")
      dev_line=(":::::::")  # don't repeat the disk info
    fi
  done < <(parted -lm)

  local columns=(DISK SIZE TYPE "SECTORS (L)" "SECTORS (P)" "PART TYP" MODEL "#"  START END SIZE "FILE SYSTEM" NAME FLAGS)
  local lengths=(0 0 0 0 0 0 0 0 0 0 0 0 0 0)
  lengths=($(calc_lens lengths columns))

  local output=()
  for ((i = 0; i < ${#lines[@]}; i++))
  do
    IFS=':' read -r -a output <<< "${lines[$i]}"
    lengths=($(calc_lens lengths output))
  done

  echo -e "PARTITIONS (parted)\n"
  print_line columns lengths true
  for ((i = 0; i < ${#lines[@]}; i++))
  do
    IFS=':' read -r -a output <<< "${lines[$i]}"
    print_line output lengths
  done
}

#
# Prints mounts, via the 'mount' command
#
# Params:
#
#   None
#
# Returns:
#
#   Nothing
#
function mounts() {
  local c1=0
  local c2=0
  local c3=0
  local c4=0
  local lines=()
  
  # tablulate the max length of each column so we can
  # format the data nicely
  while IFS= read -r line; do
    # retain lines for printing later
    lines=("${lines[@]}" "$line")
    # convert line to array
    line=($line)
    [[ ${#line[0]} -gt $c1 ]] && c1=${#line[0]}
    [[ ${#line[2]} -gt $c2 ]] && c2=${#line[2]}
    [[ ${#line[4]} -gt $c3 ]] && c3=${#line[4]}
    [[ ${#line[5]} -gt $c4 ]] && c4=${#line[5]}
  done < <(mount | grep -v snapd | grep -v cgroup | sort)

  # add spacing
  c1=$(($c1+2))
  c2=$(($c2+2))
  c3=$(($c3+2))
  c4=$(($c4+2))

  echo -e "MOUNTS (mount)\n"
  print_hdr "DEVICE" $c1 "MOUNTED ON" $c2 "TYPE" $c3 "FLAGS" $c4

  # print the content
  for ((i = 0; i < ${#lines[@]}; i++))
  do
    line=(${lines[$i]})
    printf "%-${c1}s%-${c2}s%-${c3}s%-${c4}s\n" ${line[0]} ${line[2]} ${line[4]} ${line[5]}
  done
}

#
# Entry point
#
parse_args "$@"
for info in "${infos[@]}"
do
  echo
  $info  # call the requested function
done
