#!/bin/bash

##
# Displays a wallpaper from the passed directory.
#
# usage:
# 
# wpslide /home/$USER/Pictures
#
# With one arg, queries gsettings for the current wallpaper and then
# displays the next sequential wallpaper from the passed directory using
# alpha sort, wrapping around to the first wallpaper.
#
# wpslide /home/$USER/Pictures random
#
# When the 'random' arg is passed as arg #2, selects a wallpaper at
# random from the passed directory and displays it.
#
# tested configuration:
#   Ubuntu 18.04.1 LTS
#   GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
#
# To set up a background process to continually cycle through the
# wallpapers in round-robin fashion:
#
# $ while true; do wpslide /home/$USER/Pictures; sleep 20m; done &
#
##

if [[ "$#" -eq 2 ]] && [[ "$2" == "random" ]]; then
  wps=$(ls "$1" | grep 'jpg$\|png$')
  wps=($wps)
  wp_cnt=${#wps[@]}
  idx=$((RANDOM % $wp_cnt))
  wp="$1"
  len=${#wp}
  ((len--))
  if ! [[ "${wp:$len:1}" == "/" ]]; then
    wp="$wp/"
  fi
  wp="$wp${wps[$idx]}"
  gsettings set org.gnome.desktop.background picture-uri "file://$wp"
  exit 0
fi

##
# holds the currently displayed wallpaper. The gsettings command returns the
# value like: 'file:///dir1/dir2/image-file.jpg'
##
current_wallpaper=$(gsettings get org.gnome.desktop.background picture-uri)

##
# maps $1 to a name: specifies the directory that contains the wallpaper image
# files
##
wallpapers="$1"
if [[ -z "$wallpapers" ]]; then
  echo "Must provide a directory. E.g.: 'wpslide /home/$USER/Pictures'"
  exit 1
fi
if [[ ! -d "$wallpapers" ]]; then
  echo "$wallpapers is not a directory"
  exit 1
fi

##
# toggles to "yes", once the script finds the currently displayed wallpaper
# in the passed wallpaper directory
##
found_current="no"

##
# saves the first wallpaper in the directory. If the currently displayed wallpaper
# is the last image in the directory, then the script wraps around to the first
# image in the directory (round-robin)
##
first_wallpaper=""

##
# main loop
##
for wallpaper in "$wallpapers"/*
do
  if [[ -d "$wallpaper" ]]
  then
    continue  # ignore directories
  fi
  if [[ -z "$first_wallpaper" ]]
  then
    first_wallpaper="$wallpaper"
    if [[ -z "$current_wallpaper" ]]
    then
      # no wallpaper is currently displayed, so display the first
      gsettings set org.gnome.desktop.background picture-uri "file://$first_wallpaper"
      exit 0
    fi
  fi
  if [[ "$found_current" == "yes" ]]
  then
    # found the current last time through, so this one is the next one after
    gsettings set org.gnome.desktop.background picture-uri "file://$wallpaper"
    exit 0
  elif [[ "'file://$wallpaper'" == "$current_wallpaper" ]]
  then
    # this entry in the directory is the one currently displayed
    found_current="yes"
  fi
done

##
# if the script read the whole directory and didn't exit, then the current is
# the last, so wrap around to the first - assuming a first was actually found
##
if [[ ! -z "$first_wallpaper" ]]
then
  gsettings set org.gnome.desktop.background picture-uri "file://$first_wallpaper"
else
  echo "$wallpapers does not appear to contain any files"
fi
